version: '3.8'

services:
  user_service:
    build: .
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      user_db:
        condition: service_healthy
    env_file:
      - .env

  user_db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: user_service_password
      POSTGRES_DB: user_service
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_service_user -d user_service" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  user_db_data:
    driver: local